<h1><u>Numpy Basics</u></h1>

* Numpy arrays are the main way we will use.
* Numpy arrays essentially comes in two flavours- <b>Vectors</b> and <b>Matrices</b>
* Vectors are strictly 1-D arrays and matrices are 2-d(<b> Note: a matrix can still have only one row or one column</b>)

<h2><u>Numpy Arrays</u></h2>

In [1]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [2]:
import numpy as np

In [3]:
# Creating 1-D Array
my_arr=np.array(my_list)
my_arr

array([1, 2, 3])

In [4]:
# Creating a Matrix
my_list2=[[1,2,3],[4,5,6],[7,8,9]]
my_mat=np.array(my_list2)
my_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<b><span style="color: green;">Usually however we'll be probbably using Numpy's own built in generational methods. Let's go through those a bit </b></span>

In [5]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [7]:
np.zeros(3) # Rreates an one dimensional array of  zeros

array([0., 0., 0.])

In [8]:
np.zeros((4,5)) # Creates an 2 dimensional array of zeros having 4 rows and 5 columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones(4) # Creates an one dimensional array of  ones

array([1., 1., 1., 1.])

In [10]:
np.ones((5,6)) # Creates an 2 dimensional array of ones having 5 rows and 6 columns

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
np.linspace(1,50,20) # Returns even;u spaced numbers in a given interval 

array([ 1.        ,  3.57894737,  6.15789474,  8.73684211, 11.31578947,
       13.89473684, 16.47368421, 19.05263158, 21.63157895, 24.21052632,
       26.78947368, 29.36842105, 31.94736842, 34.52631579, 37.10526316,
       39.68421053, 42.26315789, 44.84210526, 47.42105263, 50.        ])

In [12]:
np.linspace(1,4,7)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [13]:
np.eye(4) # Creates a 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand(5) # Creates an one dimensioanl array from a uniform distribution over 0-1

array([0.31966278, 0.59711035, 0.11430487, 0.07370127, 0.07440337])

In [15]:
np.random.rand(4,5) # Creates an 2 dimensional array of numbers sampled from a uniform distribution over 0-1 having 4 rows and 5 columns

array([[0.00647549, 0.49960602, 0.56100898, 0.73385111, 0.29917997],
       [0.2097726 , 0.50190436, 0.04512724, 0.18697997, 0.92164348],
       [0.35571042, 0.0807299 , 0.71386528, 0.04225033, 0.18379695],
       [0.60820387, 0.13471077, 0.72888238, 0.02034693, 0.45443423]])

In [16]:
np.random.randn(5) # Creates an one dimensioanl array from a standard normal distribution

array([-1.01570116, -0.74664448,  0.8161326 , -1.24371476, -0.45459526])

In [17]:
np.random.randn(4,5) # Creates an 2 dimensional array of numbers sampled from a standard normal distribution having 4 rows and 5 columns

array([[ 0.91027235, -0.08894801,  0.23723907, -0.73496477, -1.28657091],
       [-0.08279575, -0.26636883, -0.39255811, -0.01033467,  0.53908679],
       [ 0.47428311, -1.25846385,  0.71240463,  1.48425499,  0.75705037],
       [ 1.21450837, -0.89535904,  0.70161883,  0.36769644,  0.3716427 ]])

In [18]:
np.random.randint(1,100,10) # Creates an one dimensional array of 10 integers between 1(inclusive) and 100(exclusive)

array([96, 75, 69, 53, 45, 80,  9, 90, 32, 35], dtype=int32)

In [19]:
np.random.randint(1,100,(3,4)) # Creates a 3x4 matrix with integers sampled between 1(inclusive) and 100(exclusive)

array([[34, 70, 67, 47],
       [61, 29, 19, 92],
       [49, 68, 49,  8]], dtype=int32)

<b><span style="color: Green;">One of the most useful method in Numpy is the reshape method.</span></b>

In [20]:
ranarr=np.random.randint(0,100,10)
ranarr

array([67, 10, 85, 21, 97, 74, 33, 34, 51,  8], dtype=int32)

In [21]:
ranarr.reshape(5,2) # Reshapes the 1 dimensional array given above, into a 5x2 Matrix

array([[67, 10],
       [85, 21],
       [97, 74],
       [33, 34],
       [51,  8]], dtype=int32)

<b><span style="color: red;"> Note: The dimension of matrix created here must follow the number of elements in the primary array</b></span>

In [22]:
ranarr.max() # Gives you the max element in the array

np.int32(97)

In [23]:
ranarr.min() # Gives you the min element in the array

np.int32(8)

In [24]:
ranarr.argmax() # Gives you the index value corresponding to the max value

np.int64(4)

In [25]:
ranarr.argmin() # Gives you the index value corresponding to the min value

np.int64(9)

In [26]:
ranarr.shape 

(10,)

In [27]:
ranarr.reshape(2,5).shape

(2, 5)

<h2><u>Array Indexing</h2></u>

In [28]:
arr2=np.random.randint(0,11,10)
arr2

array([ 0, 10,  2,  9,  0,  1, 10,  1,  8,  6], dtype=int32)

In [29]:
arr2[8] # Gives you the value corresponding to the index 8

np.int32(8)

In [30]:
arr2[1:5] # Gives you the value corresponding to the indices 1-5(not included),i.e 1,2,3,4 index values

array([10,  2,  9,  0], dtype=int32)

In [31]:
arr2[5:] # Gives you all the elements beyond index 5 to the end

array([ 1, 10,  1,  8,  6], dtype=int32)

<b><span style="color: yellow;"><u>There is something very interesting that needs to be discussed</b></u></span>

Suppose we have an array

In [32]:
arr3=np.arange(0,11)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
slice_of_array=arr3[1:5]
slice_of_array

array([1, 2, 3, 4])

In [34]:
slice_of_array[:]=99
slice_of_array

array([99, 99, 99, 99])

<b><span style="color: red;">But in the original array, arr3, the same change will be reflected<b></span>

In [35]:
arr3

array([ 0, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

And the reason it does that is to avoid memory issues with very large arrays meaning numpy is not going
to automatically set copies of arrays.

In [36]:
arr3_copy=arr3.copy()
arr3_copy

array([ 0, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [37]:
arr3_copy[:]=np.arange(0,11)
arr3_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr3 # Remains the same

array([ 0, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

<h2><u> 2-D Array/Matrix Indexing </u></h>

In [39]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr_2d[1][2] # Gives you the number corresponding to row index 1 and column index 2

np.int64(6)

In [41]:
arr_2d[1,2] # Gives you the number corresponding to row index 1 and column index 2

np.int64(6)

In [42]:
arr_2d[0:2,0:2] # Top left corner

array([[1, 2],
       [4, 5]])

In [43]:
arr_2d[1:,0:2] # Bottom left corner

array([[4, 5],
       [7, 8]])

In [44]:
arr_2d[0:2,1:] # Top right corner

array([[2, 3],
       [5, 6]])

In [45]:
arr_2d[1:,1:] # Bottom eright corner

array([[5, 6],
       [8, 9]])

In [46]:
arr2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [47]:
arr2d[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [48]:
arr2d[3, ]

array([13, 14, 15, 16])

In [49]:
arr2d[:,3]

array([ 4,  8, 12, 16])

In [50]:
arr2d[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

<h2><u>Numpy Operations</u></h2>

* Array with array operations
* Array with scalars
* Universal array functions

In [56]:
arr2

array([ 0, 10,  2,  9,  0,  1, 10,  1,  8,  6], dtype=int32)

In [57]:
arr2+arr2

array([ 0, 20,  4, 18,  0,  2, 20,  2, 16, 12], dtype=int32)

In [58]:
arr2*arr2

array([  0, 100,   4,  81,   0,   1, 100,   1,  64,  36], dtype=int32)

In [59]:
arr2+100

array([100, 110, 102, 109, 100, 101, 110, 101, 108, 106], dtype=int32)

In [60]:
arr2*3

array([ 0, 30,  6, 27,  0,  3, 30,  3, 24, 18], dtype=int32)

In [61]:
arr2/arr2

C:\Users\apara\AppData\Local\Temp\ipykernel_38560\4263725751.py:1: RuntimeWarning: invalid value encountered in divide
  arr2/arr2


array([nan,  1.,  1.,  1., nan,  1.,  1.,  1.,  1.,  1.])

Notice that 0/0 didn't give us an error but a warning here

In [62]:
arr2**2

array([  0, 100,   4,  81,   0,   1, 100,   1,  64,  36], dtype=int32)

<b> <span style="color: Green;">For universal functions we can refer to  [ufunc documentation](https://numpy.org/doc/stable/reference/ufuncs.html) to go through Math Operations,Trigonometric Functions,Floating Functions, Bit Twiddling Functions and Comparison Functions.  
Refer to this [link](https://numpy.org/doc/stable/reference/ufuncs.html) to go through the same.</b></span>  